---
# This is the file used by Ansible to provision your project
# You can decide what you want to install in your box by choosing
# various provided roles or add tasks to this file. If you need
# more explanation, please refer to the drifter README

# For some part, multiple roles are proposed, just uncomment the ones
# you need.

- hosts: all
  vars_files:
   - parameters.yml
  become: no

  roles:
    ## Install some base packages and configuration files, this should be ok for all projects
    - { role: base }
    - { role: git }

    ## Scripting / Language support
    # - { role: php-fpm,  nginx_site_template: "symfony2-site.j2" }
    # - { role: php-apache }    # PHP using Apache and mod-php
    # - { role: django }        # Django framework

    ## Install Composer in the box
    # - { role: composer }

    # If you want php xdebug in your local boxes, uncomment this
    # The when clause prevents it to be installed on the CI_SERVER
    # - { role: php-xdebug, when: "'{{ lookup('env','CI_SERVER') }}' != 'yes'" }

    ## Install the ssh rule, installs gitlab.liip.ch and github.com host key
    - { role: ssh }

    ## Install neo4j
    - { role: neo4j }

# If needed, you can specify your own tasks, here is an example :
#  tasks:
#    - name: install project dev tools
#      shell: cd {{ root_directory }} && composer.phar --quiet install
#    - name: Copy application config file
#      shell: cp -f {{ root_directory }}/config/server_config.php.vagrant {{ root_directory }}/config/server_config.php
#    - name: Provision the database
#      shell: cd {{ root_directory }} && ./console mysql:reset
